openapi: "3.0.0"
info:

  title: Sneaker Store API
  description: RESPI API
  contact:
    name: Vadim
    url: https://apisneakerstore.herokuapp.com/
    email: vadimbelaev002@gmail.com
  version: 1.2.0